<template>
  <div class="report-settings">
    <div class="settings-container">
      <!-- Page Header -->
      <div class="page-header">
        <h2 class="text-title-large text-neutral-800">报告偏好</h2>
        <p class="mt-2 text-body-medium text-neutral-600">自定义报告生成和显示的各项设置</p>
      </div>

      <!-- Generation Settings -->
      <section class="settings-section">
        <div class="section-header">
          <h3 class="text-title-medium text-neutral-800">生成设置</h3>
          <p class="text-body-small text-neutral-600">配置报告自动生成和默认参数</p>
        </div>

        <div class="settings-form">
          <div class="form-group">
            <div class="setting-item">
              <div class="setting-info">
                <label class="setting-label">自动生成每日报告</label>
                <p class="setting-description">每天自动分析聊天记录并生成报告</p>
              </div>
              <div class="setting-control">
                <div
                  class="toggle-switch"
                  :class="{ active: reportPreferences.autoGenerateDaily }"
                  @click="
                    reportPreferences.autoGenerateDaily = !reportPreferences.autoGenerateDaily
                  "
                >
                  <div class="toggle-handle"></div>
                </div>
              </div>
            </div>
          </div>

          <div v-if="reportPreferences.autoGenerateDaily" class="form-group">
            <label class="form-label">生成时间</label>
            <input v-model="reportPreferences.dailyGenerationTime" type="time" class="form-input" />
          </div>

          <div class="form-group">
            <label class="form-label">默认分析深度</label>
            <select v-model="reportPreferences.defaultAnalysisDepth" class="form-select">
              <option value="basic">基础分析</option>
              <option value="detailed">详细分析</option>
              <option value="comprehensive">全面分析</option>
            </select>
          </div>

          <div class="form-group">
            <label class="form-label">报告语言</label>
            <select v-model="reportPreferences.language" class="form-select">
              <option value="zh">中文</option>
              <option value="en">English</option>
            </select>
          </div>

          <div class="form-group">
            <label class="form-label">时区</label>
            <select v-model="reportPreferences.timezone" class="form-select">
              <option value="Asia/Shanghai">北京时间 (UTC+8)</option>
              <option value="Asia/Tokyo">东京时间 (UTC+9)</option>
              <option value="America/New_York">纽约时间 (UTC-5)</option>
              <option value="Europe/London">伦敦时间 (UTC+0)</option>
            </select>
          </div>
        </div>
      </section>

      <!-- Display Settings -->
      <section class="settings-section">
        <div class="section-header">
          <h3 class="text-title-medium text-neutral-800">显示设置</h3>
          <p class="text-body-small text-neutral-600">自定义报告的显示方式和阅读体验</p>
        </div>

        <div class="settings-form">
          <div class="form-group">
            <label class="form-label">字体大小</label>
            <div class="font-size-control">
              <Button variant="text" size="sm" icon="minus" @click="decreaseFontSize" />
              <span class="font-size-value">{{ displaySettings.fontSize }}px</span>
              <Button variant="text" size="sm" icon="plus" @click="increaseFontSize" />
            </div>
          </div>

          <div class="form-group">
            <label class="form-label">行间距</label>
            <select v-model="displaySettings.lineHeight" class="form-select">
              <option value="1.4">紧凑 (1.4)</option>
              <option value="1.6">标准 (1.6)</option>
              <option value="1.8">宽松 (1.8)</option>
              <option value="2.0">很宽松 (2.0)</option>
            </select>
          </div>

          <div class="form-group">
            <div class="setting-item">
              <div class="setting-info">
                <label class="setting-label">显示阅读进度</label>
                <p class="setting-description">在报告页面显示阅读进度条</p>
              </div>
              <div class="setting-control">
                <div
                  class="toggle-switch"
                  :class="{ active: displaySettings.showReadingProgress }"
                  @click="
                    displaySettings.showReadingProgress = !displaySettings.showReadingProgress
                  "
                >
                  <div class="toggle-handle"></div>
                </div>
              </div>
            </div>
          </div>

          <div class="form-group">
            <div class="setting-item">
              <div class="setting-info">
                <label class="setting-label">自动保存阅读位置</label>
                <p class="setting-description">记住每个报告的阅读位置</p>
              </div>
              <div class="setting-control">
                <div
                  class="toggle-switch"
                  :class="{ active: displaySettings.autoSavePosition }"
                  @click="displaySettings.autoSavePosition = !displaySettings.autoSavePosition"
                >
                  <div class="toggle-handle"></div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>

      <!-- Notification Settings -->
      <section class="settings-section">
        <div class="section-header">
          <h3 class="text-title-medium text-neutral-800">通知设置</h3>
          <p class="text-body-small text-neutral-600">管理报告相关的通知和提醒</p>
        </div>

        <div class="settings-form">
          <div class="form-group">
            <div class="setting-item">
              <div class="setting-info">
                <label class="setting-label">报告生成完成通知</label>
                <p class="setting-description">报告生成完成时显示通知</p>
              </div>
              <div class="setting-control">
                <div
                  class="toggle-switch"
                  :class="{ active: notificationSettings.reportGenerated }"
                  @click="
                    notificationSettings.reportGenerated = !notificationSettings.reportGenerated
                  "
                >
                  <div class="toggle-handle"></div>
                </div>
              </div>
            </div>
          </div>

          <div class="form-group">
            <div class="setting-item">
              <div class="setting-info">
                <label class="setting-label">每日报告提醒</label>
                <p class="setting-description">提醒查看每日生成的报告</p>
              </div>
              <div class="setting-control">
                <div
                  class="toggle-switch"
                  :class="{ active: notificationSettings.dailyReminder }"
                  @click="notificationSettings.dailyReminder = !notificationSettings.dailyReminder"
                >
                  <div class="toggle-handle"></div>
                </div>
              </div>
            </div>
          </div>

          <div class="form-group">
            <div class="setting-item">
              <div class="setting-info">
                <label class="setting-label">每周摘要</label>
                <p class="setting-description">每周发送报告摘要通知</p>
              </div>
              <div class="setting-control">
                <div
                  class="toggle-switch"
                  :class="{ active: notificationSettings.weeklyDigest }"
                  @click="notificationSettings.weeklyDigest = !notificationSettings.weeklyDigest"
                >
                  <div class="toggle-handle"></div>
                </div>
              </div>
            </div>
          </div>

          <div class="form-group">
            <div class="setting-item">
              <div class="setting-info">
                <label class="setting-label">错误警告</label>
                <p class="setting-description">报告生成失败时显示警告</p>
              </div>
              <div class="setting-control">
                <div
                  class="toggle-switch"
                  :class="{ active: notificationSettings.errorAlerts }"
                  @click="notificationSettings.errorAlerts = !notificationSettings.errorAlerts"
                >
                  <div class="toggle-handle"></div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>

      <!-- Export Settings -->
      <section class="settings-section">
        <div class="section-header">
          <h3 class="text-title-medium text-neutral-800">导出设置</h3>
          <p class="text-body-small text-neutral-600">配置报告导出的默认格式和选项</p>
        </div>

        <div class="settings-form">
          <div class="form-group">
            <label class="form-label">默认导出格式</label>
            <div class="format-options">
              <div
                v-for="format in exportFormats"
                :key="format.id"
                class="format-option"
                :class="{ selected: exportSettings.defaultFormat === format.id }"
                @click="exportSettings.defaultFormat = format.id"
              >
                <Icon :name="format.icon" :size="20" />
                <div class="format-info">
                  <div class="format-name">{{ format.name }}</div>
                  <div class="format-description">{{ format.description }}</div>
                </div>
              </div>
            </div>
          </div>

          <div class="form-group">
            <div class="setting-item">
              <div class="setting-info">
                <label class="setting-label">包含图表</label>
                <p class="setting-description">导出时包含数据可视化图表</p>
              </div>
              <div class="setting-control">
                <div
                  class="toggle-switch"
                  :class="{ active: exportSettings.includeCharts }"
                  @click="exportSettings.includeCharts = !exportSettings.includeCharts"
                >
                  <div class="toggle-handle"></div>
                </div>
              </div>
            </div>
          </div>

          <div class="form-group">
            <div class="setting-item">
              <div class="setting-info">
                <label class="setting-label">包含原始数据</label>
                <p class="setting-description">导出时包含分析使用的原始数据</p>
              </div>
              <div class="setting-control">
                <div
                  class="toggle-switch"
                  :class="{ active: exportSettings.includeRawData }"
                  @click="exportSettings.includeRawData = !exportSettings.includeRawData"
                >
                  <div class="toggle-handle"></div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>

      <!-- Preview Section -->
      <section class="settings-section">
        <div class="section-header">
          <h3 class="text-title-medium text-neutral-800">预览</h3>
          <p class="text-body-small text-neutral-600">查看当前设置的效果预览</p>
        </div>

        <div class="preview-container">
          <div
            class="preview-content"
            :style="{
              fontSize: displaySettings.fontSize + 'px',
              lineHeight: displaySettings.lineHeight
            }"
          >
            <h4 class="preview-title">示例报告标题</h4>
            <p class="preview-text">
              这是一段示例文本，用于预览当前的字体大小和行间距设置。
              您可以调整上面的设置来查看不同的显示效果。 这段文字会根据您的设置实时更新显示样式。
            </p>
            <div v-if="displaySettings.showReadingProgress" class="preview-progress">
              <div class="progress-bar">
                <div class="progress-fill" style="width: 60%"></div>
              </div>
              <span class="progress-text">阅读进度: 60%</span>
            </div>
          </div>
        </div>
      </section>

      <!-- Action Buttons -->
      <div class="actions-section">
        <div class="actions-buttons">
          <Button variant="secondary" size="md" icon="refresh-cw" @click="resetToDefaults">
            重置为默认
          </Button>

          <Button variant="primary" size="md" icon="save" :loading="isSaving" @click="saveSettings">
            保存设置
          </Button>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, onMounted } from 'vue'
import Button from '@renderer/components/design-system/Button.vue'
import Icon from '@renderer/components/design-system/Icon.vue'
import type { ReportPreferences, NotificationSettings } from '@renderer/types/pages'

// Reactive state
const isSaving = ref(false)

const reportPreferences = ref<ReportPreferences>({
  defaultAnalysisDepth: 'detailed',
  autoGenerateDaily: true,
  language: 'zh',
  timezone: 'Asia/Shanghai',
  dailyGenerationTime: '09:00',
  notificationSettings: {
    reportGenerated: true,
    dailyReminder: true,
    weeklyDigest: false,
    errorAlerts: true
  }
})

const displaySettings = ref({
  fontSize: 16,
  lineHeight: '1.6',
  showReadingProgress: true,
  autoSavePosition: true
})

const notificationSettings = ref<NotificationSettings>({
  reportGenerated: true,
  dailyReminder: true,
  weeklyDigest: false,
  errorAlerts: true
})

const exportSettings = ref({
  defaultFormat: 'pdf',
  includeCharts: true,
  includeRawData: false
})

const exportFormats = [
  {
    id: 'pdf',
    name: 'PDF',
    description: '适合打印和分享',
    icon: 'file-text'
  },
  {
    id: 'html',
    name: 'HTML',
    description: '网页格式，支持交互',
    icon: 'globe'
  },
  {
    id: 'markdown',
    name: 'Markdown',
    description: '纯文本格式，易于编辑',
    icon: 'edit'
  },
  {
    id: 'json',
    name: 'JSON',
    description: '结构化数据格式',
    icon: 'code'
  }
]

// Methods
const increaseFontSize = () => {
  if (displaySettings.value.fontSize < 24) {
    displaySettings.value.fontSize += 1
  }
}

const decreaseFontSize = () => {
  if (displaySettings.value.fontSize > 12) {
    displaySettings.value.fontSize -= 1
  }
}

const resetToDefaults = () => {
  reportPreferences.value = {
    defaultAnalysisDepth: 'detailed',
    autoGenerateDaily: true,
    language: 'zh',
    timezone: 'Asia/Shanghai',
    dailyGenerationTime: '09:00',
    notificationSettings: {
      reportGenerated: true,
      dailyReminder: true,
      weeklyDigest: false,
      errorAlerts: true
    }
  }

  displaySettings.value = {
    fontSize: 16,
    lineHeight: '1.6',
    showReadingProgress: true,
    autoSavePosition: true
  }

  notificationSettings.value = {
    reportGenerated: true,
    dailyReminder: true,
    weeklyDigest: false,
    errorAlerts: true
  }

  exportSettings.value = {
    defaultFormat: 'pdf',
    includeCharts: true,
    includeRawData: false
  }
}

const saveSettings = async () => {
  isSaving.value = true

  try {
    // TODO: Implement actual settings save
    await new Promise((resolve) => setTimeout(resolve, 1000))

    // Show success message
  } catch (error) {
    // Show error message
  } finally {
    isSaving.value = false
  }
}

// Lifecycle
onMounted(async () => {
  // Load existing settings
  // TODO: Implement settings loading
})
</script>

<style scoped>
.report-settings {
  @apply p-6;
}

.settings-container {
  @apply space-y-8;
}

.page-header {
  @apply mb-8;
}

.settings-section {
  @apply bg-white p-6 rounded-lg shadow-sm;
}

.section-header {
  @apply mb-6;
}

.settings-form {
  @apply space-y-6;
}

.form-group {
  @apply space-y-2;
}

.form-label {
  @apply text-sm font-medium text-neutral-700;
}

.form-input,
.form-select {
  @apply w-full px-3 py-2 border border-neutral-300 rounded-md;
}

.setting-item {
  @apply flex items-center justify-between p-4 border border-neutral-200 rounded-lg;
}

.setting-info {
  @apply flex-1;
}

.setting-label {
  @apply font-medium text-neutral-800;
}

.setting-description {
  @apply text-sm text-neutral-600 mt-1;
}

.toggle-switch {
  @apply w-12 h-6 bg-neutral-300 rounded-full relative cursor-pointer transition-colors;
}

.toggle-switch.active {
  @apply bg-primary-500;
}

.toggle-handle {
  @apply w-5 h-5 bg-white rounded-full absolute top-0.5 left-0.5 transition-transform;
}

.toggle-switch.active .toggle-handle {
  @apply transform translate-x-6;
}

.font-size-control {
  @apply flex items-center space-x-4;
}

.font-size-value {
  @apply text-sm font-medium text-neutral-700 min-w-12 text-center;
}

.format-options {
  @apply grid grid-cols-1 md:grid-cols-2 gap-3;
}

.format-option {
  @apply flex items-center space-x-3 p-4 border border-neutral-200 rounded-lg cursor-pointer transition-colors hover:border-neutral-300;
}

.format-option.selected {
  @apply border-primary-500 bg-primary-50;
}

.format-info {
  @apply flex-1;
}

.format-name {
  @apply font-medium text-neutral-800;
}

.format-description {
  @apply text-sm text-neutral-600;
}

.preview-container {
  @apply bg-neutral-50 p-6 rounded-lg;
}

.preview-content {
  @apply bg-white p-6 rounded-lg shadow-sm;
}

.preview-title {
  @apply font-semibold text-neutral-800 mb-4;
}

.preview-text {
  @apply text-neutral-700 mb-4;
}

.preview-progress {
  @apply space-y-2;
}

.progress-bar {
  @apply w-full h-2 bg-neutral-200 rounded-full;
}

.progress-fill {
  @apply h-full bg-primary-500 rounded-full transition-all;
}

.progress-text {
  @apply text-sm text-neutral-600;
}

.actions-section {
  @apply bg-white p-6 rounded-lg shadow-sm;
}

.actions-buttons {
  @apply flex items-center justify-end space-x-3;
}
</style>
